### ISSUE TITLE
eip_config中的地址可以支持数组模式吗

### ISSUE THREAD

**Issue by xmapst** [kubesphere/porterlb#127]
默认只支持字符串类型
```yaml
apiVersion: network.kubesphere.io/v1alpha1
kind: Eip
metadata:
    name: eip-sample-pool
spec:
    address: 192.168.0.0/24
    protocol: layer2
```
能不能实现为以下类型的
```yaml
apiVersion: network.kubesphere.io/v1alpha1
kind: Eip
metadata:
    name: eip-sample-pool
spec:
    address: 
    - 192.168.10.5-192.168.10.50
    - 192.168.10.100
    - 192.168.10.150-192.168.10.151
    protocol: layer2
    disable: false
```
