### ISSUE TITLE
invalid eip address format

### ISSUE THREAD

**Issue by ruckc** [kubesphere/porterlb#200]
I'm trying to use porterlb, but the validation webhook is failing a copy+paste of the documentation's [layer2 ](https://porterlb.io/docs/getting-started/configuration/configure-ip-address-pools-using-eip/#configure-an-eip-object-for-porterlb) example.

I get this output from the eip yaml:

`admission webhook "validate.eip.network.kubesphere.io" denied the request: invalid eip address format`

```yaml
apiVersion: network.kubesphere.io/v1alpha2
kind: Eip
metadata:
    name: eip-sample-pool
spec:
    address: 192.168.0.91-192.168.0.100
    protocol: layer2
    interface: eth0
    disable: false
```

It appears around the parsing logic there is no debug logging.  I'm running the latest version 0.4.1 on arm64.
